### ISSUE TITLE
Time for a dep bump?

### ISSUE THREAD

**Issue by shymega** [Wilfred/tree-sitter-elisp#4]
Hi @Wilfred!

Admired your Emacs advocacy for many years, so I'm glad of an opportunity to discuss Elisp with you.

I've been writing a [parser](https://github.com/shymega/emacsconf2nix) in Rust (for Nix) to be used with Emacs Lisp, and I decided to use `tree-sitter` and this grammar repo. However, I immediately ran into a conflict with the two `tree-sitter` versions and had to [fork](https://github.com/shymega/tree-sitter-elisp/tree/shymega/bump-ver), bump `tree-sitter`, push, and then patch with Cargo.

I was wondering if you would be able to issue a new release on Crates.io with the latest version of TS.

That would be awesome if you could. That way I don't have to use a fork. Happy to make a PR from my branch too.

Thanks!

**Comment by Wilfred** [comment]
Thanks for your kind words :)

I've updated tree-sitter-cli, regenerated the parser, and cut a release on both npm and crates.io with the latest tree-sitter library. Shout if I've missed anything.

**Comment by shymega** [comment]
Thank you! Appreciated.
